### ISSUE TITLE
Backend crash on endpoint /api/users/me

### ISSUE THREAD

**Issue by tercsd** [xKeiro/jedlik-vizsgaremek#1]
Everytime fails with valid login credentials (also on postman):
```
INFO:     127.0.0.1:49168 - "GET /api/users/me HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/tercsd/jedlik-vizsgaremek/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/tercsd/jedlik-vizsgaremek/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/tercsd/jedlik-vizsgaremek/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/tercsd/jedlik-vizsgaremek/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/tercsd/jedlik-vizsgaremek/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/tercsd/jedlik-vizsgaremek/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/tercsd/jedlik-vizsgaremek/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/tercsd/jedlik-vizsgaremek/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/home/tercsd/jedlik-vizsgaremek/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/home/tercsd/jedlik-vizsgaremek/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/tercsd/jedlik-vizsgaremek/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/tercsd/jedlik-vizsgaremek/.venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/home/tercsd/jedlik-vizsgaremek/.venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/home/tercsd/jedlik-vizsgaremek/.venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/tercsd/jedlik-vizsgaremek/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 249, in app
    content = await serialize_response(
  File "/home/tercsd/jedlik-vizsgaremek/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 138, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for UserResponse
response
  value is not a valid dict (type=type_error.dict)
```

**Comment by xKeiro** [comment]
Fixed in commit e4134cfb05ce13a0b0df61b22e3a36899ecccedf
